[package]
name = "stats"
version = "0.1.0"
authors = ["workpef <47220333+workpef@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
